### ISSUE TITLE
Uploading Profile pic with cyrillic name gets server error

### ISSUE THREAD

**Issue by BoyanTodorov** [HackBulgaria/Odin#63]
![servererror](https://cloud.githubusercontent.com/assets/4215769/6096798/3faa5852-afad-11e4-92f7-8286a75839f8.png) 
I tried to upload profile pic, that was named with cyrillic letters and i get that error message. 
When I changed the name to be with latin letters everything is OK.

**Comment by Ivaylo-Bachvarov** [comment]
Thanks for that report. It is a server issue. I dont tink it is related to the project. I will check it as soon as posible. 

:beers:

**Comment by RadoRado** [comment]
@BoyanTodorov  thanks for the feedback - we will check this out ^_^ :panda_face:

**Comment by Ivaylo-Bachvarov** [comment]
Fixed! It was not related to the project. It was deploy problem. Not it is fixed! :panda_face:
